# Configurazione Connessione Database (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.sijkmtytmpmigzypqoid
spring.datasource.password=torneidaniele10
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
# 'update' crea o aggiorna automaticamente le tabelle nel database basandosi sulle classi @Entity [cite: 7]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurazione Thymeleaf (Frontend)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html