# Sostituisci [password] e [host] con i tuoi dati Supabase
spring.datasource.url=jdbc:postgresql://sijkmtytmpmigzypqoid:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=torneidaniele10

# Importante per far creare le tabelle a Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect