# Configurazione Connessione Database (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.sijkmtytmpmigzypqoid
spring.datasource.password=torneidaniele10
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
# 'update' crea o aggiorna automaticamente le tabelle nel database basandosi sulle classi @Entity [cite: 7]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurazione Thymeleaf (Frontend)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# --- CONFIGURAZIONE GOOGLE OAUTH2 ---
spring.security.oauth2.client.registration.google.client-id=466659887369-ehm0bt7kg5618lofcjhntme0d6ggd2f8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile, email